from .base import BASE_ENV



DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"
STATICFILES_STORAGE = "minio_storage.storage.MinioStaticStorage"
MINIO_STORAGE_ENDPOINT = BASE_ENV("MINIO_ENDPOINT")
MINIO_EXTERNAL_STORAGE_ENDPOINT = BASE_ENV("MINIO_EXTERNAL_ENDPOINT")

MINIO_STORAGE_ACCESS_KEY = BASE_ENV("MINIO_ACCESS_KEY")
MINIO_STORAGE_SECRET_KEY = BASE_ENV("MINIO_SECRET_KEY")
MINIO_STORAGE_USE_HTTPS = False

MINIO_STORAGE_MEDIA_OBJECT_METADATA = {"Cache-Control": "max-age=1000"}
MINIO_STORAGE_MEDIA_BACKUP_BUCKET = "Recycle Bin"
MINIO_STORAGE_MEDIA_BACKUP_FORMAT = "%c/"

MINIO_STORAGE_MEDIA_BUCKET_NAME = "local-media"
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True

MINIO_STORAGE_STATIC_BUCKET_NAME = "local-static"
MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = True

MINIO_STORAGE_STATIC_URL = (
    f"{MINIO_EXTERNAL_STORAGE_ENDPOINT}/{MINIO_STORAGE_STATIC_BUCKET_NAME}"
)
MINIO_STORAGE_MEDIA_URL = (
    f"{MINIO_EXTERNAL_STORAGE_ENDPOINT}/{MINIO_STORAGE_MEDIA_BUCKET_NAME}"
)
