from ..base import BASE_ENV

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = BASE_ENV("EMAIL")
EMAIL_HOST_PASSWORD = BASE_ENV("EMAIL_PASSWORD")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
