# Generated by Django 4.2.5 on 2023-10-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTracking",
            fields=[
                (
                    "user_id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("last_login", models.DateTimeField()),
                ("last_userlogin", models.DateTimeField()),
                (
                    "login_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("refresh", "Refresh"),
                            ("access", "Access"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("user_agent", models.TextField()),
                ("ip", models.GenericIPAddressField()),
            ],
        ),
    ]
