# Generated by Django 4.2.5 on 2023-10-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_usertracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertracking",
            name="ip",
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name="usertracking",
            name="login_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("refresh", "Refresh"),
                    ("access", "Access"),
                    ("other", "Other"),
                    ("register", "Register"),
                ],
                default="register",
                max_length=10,
            ),
        ),
    ]
