# Generated by Django 4.2.5 on 2023-10-20 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_usertracking_ip_alter_usertracking_login_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertracking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usertracking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
