from ...base import BASE_ENV


CELERY_BROKER_URL = BASE_ENV("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = BASE_ENV("CELERY_RESULT_BACKEND")

CELERY_MAX_CONCURRENCY = 5
CELERY_MAX_RETRY = 6

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
