# Generated by Django 4.2.5 on 2023-10-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0002_alter_podcastepisode_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcastepisodepaths",
            name="route_name",
            field=models.CharField(default="x", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="podcastrsspaths",
            name="route_name",
            field=models.CharField(default="X", max_length=50),
            preserve_default=False,
        ),
    ]
