# Generated by Django 4.2.5 on 2023-10-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0004_alter_podcastepisode_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcastepisode",
            name="image",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="podcastmainfields",
            name="copyright",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="podcastmainfields",
            name="explicit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="podcastmainfields",
            name="host",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="podcastmainfields",
            name="image",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="podcastmainfields",
            name="language",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="podcastmainfields",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
